//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_GPHEADER_VIEW
    {
        public int gp_id { get; set; }
        public string gp_name { get; set; }
        public int gp_srs { get; set; }
        public System.DateTime gp_deldate { get; set; }
        public System.DateTime gp_datecrtd { get; set; }
        public int drvr_id { get; set; }
        public int usr_id { get; set; }
        public int gpstat_id { get; set; }
        public string drvr_name { get; set; }
        public string crtdby { get; set; }
        public string gpstat_name { get; set; }
        public int drvr_usr_id { get; set; }
        public Nullable<System.DateTime> crr_synced { get; set; }
        public Nullable<System.DateTime> crr_completed { get; set; }
        public Nullable<int> crr_cashier { get; set; }
        public string xuser { get; set; }
    }
}
