//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_MSTR_CUST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_MSTR_CUST()
        {
            this.FDR_ORD_HEADER = new HashSet<FDR_ORD_HEADER>();
        }
    
        public string cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public string salesman_id { get; set; }
        public string site_id { get; set; }
        public Nullable<double> cust_latitude { get; set; }
        public Nullable<double> cust_longitude { get; set; }
        public int stat_id { get; set; }
        public System.DateTime cust_datecrtd { get; set; }
        public Nullable<System.DateTime> cust_dateuptd { get; set; }
        public int cust_crtdby { get; set; }
        public Nullable<int> cust_uptdby { get; set; }
    
        public virtual FDR_MSTR_SITE FDR_MSTR_SITE { get; set; }
        public virtual FDR_MSTR_SLSMAN FDR_MSTR_SLSMAN { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS1 { get; set; }
        public virtual FDR_TYPE_STAT FDR_TYPE_STAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_ORD_HEADER> FDR_ORD_HEADER { get; set; }
    }
}
