//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_CO_LINES
    {
        public int col_id { get; set; }
        public int co_id { get; set; }
        public string invty_id { get; set; }
        public int col_qty { get; set; }
        public int cot_id { get; set; }
        public int uom_id { get; set; }
        public Nullable<decimal> bag_barcode_id { get; set; }
    
        public virtual FDR_CO_HEADER FDR_CO_HEADER { get; set; }
        public virtual FDR_MSTR_INVTY FDR_MSTR_INVTY { get; set; }
        public virtual FDR_TYPE_CO FDR_TYPE_CO { get; set; }
        public virtual FDR_TYPE_UOM FDR_TYPE_UOM { get; set; }
    }
}
