//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_CO_VIEW
    {
        public int col_id { get; set; }
        public string ord_number { get; set; }
        public string invty_id { get; set; }
        public int uom_id { get; set; }
        public string uom_desc { get; set; }
        public int col_qty { get; set; }
        public Nullable<long> crate_id { get; set; }
        public string cot_desc { get; set; }
        public string invty_desc { get; set; }
        public string crate_desc { get; set; }
        public Nullable<int> crate_qty { get; set; }
    }
}
