//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_MSTR_SITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_MSTR_SITE()
        {
            this.FDR_MSTR_CUST = new HashSet<FDR_MSTR_CUST>();
            this.FDR_MSTR_JRSLSMAN = new HashSet<FDR_MSTR_JRSLSMAN>();
            this.FDR_MSTR_SLSMAN = new HashSet<FDR_MSTR_SLSMAN>();
        }
    
        public string site_id { get; set; }
        public string site_name { get; set; }
        public System.DateTime site_datecrtd { get; set; }
        public Nullable<System.DateTime> site_dateuptd { get; set; }
        public int site_crtdby { get; set; }
        public Nullable<int> site_uptdby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_CUST> FDR_MSTR_CUST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_JRSLSMAN> FDR_MSTR_JRSLSMAN { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_SLSMAN> FDR_MSTR_SLSMAN { get; set; }
    }
}
