//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_ORD_LINES
    {
        public int ord_line_id { get; set; }
        public string ord_number { get; set; }
        public string invty_id { get; set; }
        public Nullable<int> ord_r_cs { get; set; }
        public Nullable<int> ord_r_pc { get; set; }
        public Nullable<int> ord_f_cs { get; set; }
        public Nullable<int> ord_f_pc { get; set; }
        public Nullable<int> ord_pr_cs { get; set; }
        public Nullable<int> ord_pr_pc { get; set; }
        public Nullable<int> ord_pf_cs { get; set; }
        public Nullable<int> ord_pf_pc { get; set; }
        public Nullable<int> ord_nr_cs { get; set; }
        public Nullable<int> ord_nr_pc { get; set; }
        public Nullable<int> ord_nf_cs { get; set; }
        public Nullable<int> ord_nf_pc { get; set; }
    
        public virtual FDR_MSTR_INVTY FDR_MSTR_INVTY { get; set; }
        public virtual FDR_ORD_HEADER FDR_ORD_HEADER { get; set; }
    }
}
