//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_PRCNT_VIEW1
    {
        public int ord_line_id { get; set; }
        public System.DateTime ord_date { get; set; }
        public string cust_id { get; set; }
        public string cust_name { get; set; }
        public string salesman_id { get; set; }
        public string salesman_name { get; set; }
        public string ord_number { get; set; }
        public string invty_id { get; set; }
        public string invty_desc { get; set; }
        public Nullable<int> ord_r_cs { get; set; }
        public Nullable<int> ord_r_pc { get; set; }
        public Nullable<int> ord_f_cs { get; set; }
        public Nullable<int> ord_f_pc { get; set; }
        public Nullable<int> ord_pr_cs { get; set; }
        public Nullable<int> ord_pr_pc { get; set; }
        public Nullable<int> ord_pf_cs { get; set; }
        public Nullable<int> ord_pf_pc { get; set; }
        public Nullable<int> ord_nr_cs { get; set; }
        public Nullable<int> ord_nr_pc { get; set; }
        public Nullable<int> ord_nf_cs { get; set; }
        public Nullable<int> ord_nf_pc { get; set; }
        public string site_id { get; set; }
        public string invty_barcode { get; set; }
        public string invty_casecode { get; set; }
    }
}
