//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_MSTR_USRS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_MSTR_USRS()
        {
            this.FDR_CO_HEADER = new HashSet<FDR_CO_HEADER>();
            this.FDR_GP_HEADER = new HashSet<FDR_GP_HEADER>();
            this.FDR_MSTR_CUST = new HashSet<FDR_MSTR_CUST>();
            this.FDR_MSTR_CUST1 = new HashSet<FDR_MSTR_CUST>();
            this.FDR_MSTR_DEV = new HashSet<FDR_MSTR_DEV>();
            this.FDR_MSTR_DEV1 = new HashSet<FDR_MSTR_DEV>();
            this.FDR_MSTR_INVOICE = new HashSet<FDR_MSTR_INVOICE>();
            this.FDR_MSTR_INVTY = new HashSet<FDR_MSTR_INVTY>();
            this.FDR_MSTR_INVTY1 = new HashSet<FDR_MSTR_INVTY>();
            this.FDR_MSTR_JRSLSMAN = new HashSet<FDR_MSTR_JRSLSMAN>();
            this.FDR_MSTR_JRSLSMAN1 = new HashSet<FDR_MSTR_JRSLSMAN>();
            this.FDR_MSTR_JRSLSMAN2 = new HashSet<FDR_MSTR_JRSLSMAN>();
            this.FDR_MSTR_SITE = new HashSet<FDR_MSTR_SITE>();
            this.FDR_MSTR_SITE1 = new HashSet<FDR_MSTR_SITE>();
            this.FDR_MSTR_SLSMAN = new HashSet<FDR_MSTR_SLSMAN>();
            this.FDR_MSTR_SLSMAN1 = new HashSet<FDR_MSTR_SLSMAN>();
            this.FDR_ORD_STATUS_LOG = new HashSet<FDR_ORD_STATUS_LOG>();
        }
    
        public int usr_id { get; set; }
        public string usr_username { get; set; }
        public string usr_password { get; set; }
        public string usr_fname { get; set; }
        public string usr_lname { get; set; }
        public int usr_type_id { get; set; }
        public int stat_id { get; set; }
        public System.DateTime usr_datecrtd { get; set; }
        public Nullable<System.DateTime> usr_dateuptd { get; set; }
        public int usr_crtdby { get; set; }
        public Nullable<int> usr_uptdby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_CO_HEADER> FDR_CO_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_GP_HEADER> FDR_GP_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_CUST> FDR_MSTR_CUST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_CUST> FDR_MSTR_CUST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_DEV> FDR_MSTR_DEV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_DEV> FDR_MSTR_DEV1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_INVOICE> FDR_MSTR_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_INVTY> FDR_MSTR_INVTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_INVTY> FDR_MSTR_INVTY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_JRSLSMAN> FDR_MSTR_JRSLSMAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_JRSLSMAN> FDR_MSTR_JRSLSMAN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_JRSLSMAN> FDR_MSTR_JRSLSMAN2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_SITE> FDR_MSTR_SITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_SITE> FDR_MSTR_SITE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_SLSMAN> FDR_MSTR_SLSMAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_SLSMAN> FDR_MSTR_SLSMAN1 { get; set; }
        public virtual FDR_TYPE_STAT FDR_TYPE_STAT { get; set; }
        public virtual FDR_TYPE_USRS FDR_TYPE_USRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_ORD_STATUS_LOG> FDR_ORD_STATUS_LOG { get; set; }
    }
}
