//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_ORD_STATUS_LOG
    {
        public int ord_stat_log_id { get; set; }
        public string ord_number { get; set; }
        public int logt_id { get; set; }
        public System.DateTime ord_stat_datetime { get; set; }
        public int usr_id { get; set; }
    
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_ORD_HEADER FDR_ORD_HEADER { get; set; }
        public virtual FDR_TYPE_LOG FDR_TYPE_LOG { get; set; }
    }
}
