//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_TYPE_SLSMAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_TYPE_SLSMAN()
        {
            this.FDR_MSTR_JRSLSMAN = new HashSet<FDR_MSTR_JRSLSMAN>();
            this.FDR_MSTR_SLSMAN = new HashSet<FDR_MSTR_SLSMAN>();
        }
    
        public int salesman_type_id { get; set; }
        public string salesman_type_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_JRSLSMAN> FDR_MSTR_JRSLSMAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_SLSMAN> FDR_MSTR_SLSMAN { get; set; }
    }
}
