//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_CRR_DENO
    {
        public int id { get; set; }
        public int gp_id { get; set; }
        public Nullable<int> onethousand { get; set; }
        public Nullable<int> fivehundred { get; set; }
        public Nullable<int> twohundred { get; set; }
        public Nullable<int> onehundred { get; set; }
        public Nullable<int> fifty { get; set; }
        public Nullable<int> twenty { get; set; }
        public Nullable<int> ten { get; set; }
        public Nullable<int> five { get; set; }
        public Nullable<int> one { get; set; }
        public Nullable<int> twentyfivecent { get; set; }
        public Nullable<int> tencent { get; set; }
        public Nullable<int> fivecent { get; set; }
    }
}
