//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_ORD_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_ORD_HEADER()
        {
            this.FDR_CO_HEADER = new HashSet<FDR_CO_HEADER>();
            this.FDR_MSTR_INVOICE = new HashSet<FDR_MSTR_INVOICE>();
            this.FDR_ORD_LINES = new HashSet<FDR_ORD_LINES>();
            this.FDR_ORD_STATUS_LOG = new HashSet<FDR_ORD_STATUS_LOG>();
        }
    
        public string ord_number { get; set; }
        public System.DateTime ord_date { get; set; }
        public string cust_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_CO_HEADER> FDR_CO_HEADER { get; set; }
        public virtual FDR_MSTR_CUST FDR_MSTR_CUST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_INVOICE> FDR_MSTR_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_ORD_LINES> FDR_ORD_LINES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_ORD_STATUS_LOG> FDR_ORD_STATUS_LOG { get; set; }
    }
}
