//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_ITMGUIDE_VIEW2
    {
        public string ord_number { get; set; }
        public string invty_id { get; set; }
        public string invty_desc { get; set; }
        public string invty_casecode { get; set; }
        public Nullable<int> ord_pr_cs { get; set; }
        public Nullable<int> qty { get; set; }
        public string uom { get; set; }
        public string itype { get; set; }
    }
}
