//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_GATEPASS_VIEW1
    {
        public string cust_id { get; set; }
        public string cust_name { get; set; }
        public string salesman_id { get; set; }
        public string salesman_name { get; set; }
        public string type { get; set; }
        public Nullable<long> invty_id2 { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> col_qty2 { get; set; }
        public string inv_number { get; set; }
        public double inv_amount { get; set; }
        public string gp_name { get; set; }
        public System.DateTime gp_deldate { get; set; }
        public string gp_by { get; set; }
        public string drvr_name { get; set; }
        public int gp_id { get; set; }
        public int gpl_id { get; set; }
        public System.DateTime ord_date { get; set; }
        public string cust_address { get; set; }
        public string ord_number { get; set; }
        public int drvr_id { get; set; }
        public Nullable<double> cust_latitude { get; set; }
        public Nullable<double> cust_longitude { get; set; }
        public int drvr_usr_id { get; set; }
        public string gpstat_name { get; set; }
        public string sl_bcode { get; set; }
    }
}
