//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_CRRDET_VIEW
    {
        public System.DateTime ord_date { get; set; }
        public Nullable<System.DateTime> ord_date2 { get; set; }
        public string ord_number { get; set; }
        public string cust_name { get; set; }
        public string inv_number { get; set; }
        public int gp_id { get; set; }
        public int gpl_id { get; set; }
        public Nullable<double> gpl_payment { get; set; }
        public Nullable<double> gpl_redamnt { get; set; }
        public double inv_amount { get; set; }
        public string CM { get; set; }
        public string rcv_name { get; set; }
        public string salesman_id { get; set; }
        public string salesman_name { get; set; }
        public string dels_name2 { get; set; }
        public int drvr_id { get; set; }
        public string drvr_name { get; set; }
        public string Processed_By { get; set; }
        public string Picked_By { get; set; }
        public string Invoiced_By { get; set; }
        public string Scanned_By { get; set; }
        public string Staged_By { get; set; }
        public string Loaded_By { get; set; }
        public string Delivered_By { get; set; }
        public string Remmitted_By { get; set; }
    }
}
