//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_PRCNT_VIEW2
    {
        public System.DateTime ord_date { get; set; }
        public string cust_id { get; set; }
        public string cust_name { get; set; }
        public string salesman_id { get; set; }
        public string salesman_name { get; set; }
        public string ord_number { get; set; }
        public Nullable<int> t_ord_cs { get; set; }
        public Nullable<int> t_ord_pc { get; set; }
        public Nullable<int> t_ordfree_cs { get; set; }
        public Nullable<int> t_ordfree_pc { get; set; }
        public Nullable<int> t_pckd_cs { get; set; }
        public Nullable<int> t_pckd_pc { get; set; }
        public Nullable<int> t_pckdfree_cs { get; set; }
        public Nullable<int> t_pckdfree_pc { get; set; }
        public string site_id { get; set; }
        public string Status { get; set; }
        public string inv_number { get; set; }
        public Nullable<int> gpstat_id { get; set; }
    }
}
