//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_MSTR_INVTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_MSTR_INVTY()
        {
            this.FDR_CO_LINES = new HashSet<FDR_CO_LINES>();
            this.FDR_ORD_LINES = new HashSet<FDR_ORD_LINES>();
        }
    
        public string invty_id { get; set; }
        public string invty_desc { get; set; }
        public string invty_barcode { get; set; }
        public string invty_casecode { get; set; }
        public int invty_ppu { get; set; }
        public string invty_cat1 { get; set; }
        public string invty_cat2 { get; set; }
        public string invty_cat3 { get; set; }
        public string invty_cat4 { get; set; }
        public string invty_brand { get; set; }
        public int stat_id { get; set; }
        public System.DateTime invty_datecrtd { get; set; }
        public Nullable<System.DateTime> invty_dateuptd { get; set; }
        public int invty_crtdby { get; set; }
        public Nullable<int> invty_uptdby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_CO_LINES> FDR_CO_LINES { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS1 { get; set; }
        public virtual FDR_TYPE_STAT FDR_TYPE_STAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_ORD_LINES> FDR_ORD_LINES { get; set; }
    }
}
