//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_MSTR_SLSMAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_MSTR_SLSMAN()
        {
            this.FDR_MSTR_CUST = new HashSet<FDR_MSTR_CUST>();
        }
    
        public string salesman_id { get; set; }
        public string salesman_name { get; set; }
        public int salesman_type_id { get; set; }
        public string site_id { get; set; }
        public System.DateTime salesman_datecrtd { get; set; }
        public Nullable<System.DateTime> salesman_dateuptd { get; set; }
        public int salesman_crtdby { get; set; }
        public Nullable<int> salesman_uptdby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_MSTR_CUST> FDR_MSTR_CUST { get; set; }
        public virtual FDR_MSTR_SITE FDR_MSTR_SITE { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS1 { get; set; }
        public virtual FDR_TYPE_SLSMAN FDR_TYPE_SLSMAN { get; set; }
    }
}
