//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_GP_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_GP_HEADER()
        {
            this.FDR_GP_LINES = new HashSet<FDR_GP_LINES>();
            this.FDR_GP_LINES_TMP = new HashSet<FDR_GP_LINES_TMP>();
        }
    
        public int gp_id { get; set; }
        public string gp_name { get; set; }
        public int gp_srs { get; set; }
        public System.DateTime gp_deldate { get; set; }
        public System.DateTime gp_datecrtd { get; set; }
        public int drvr_id { get; set; }
        public int usr_id { get; set; }
        public int gpstat_id { get; set; }
        public Nullable<System.DateTime> crr_synced { get; set; }
        public Nullable<System.DateTime> crr_completed { get; set; }
        public Nullable<int> crr_cashier { get; set; }
    
        public virtual FDR_MSTR_JRSLSMAN FDR_MSTR_JRSLSMAN { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_TYPE_GPSTAT FDR_TYPE_GPSTAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_GP_LINES> FDR_GP_LINES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_GP_LINES_TMP> FDR_GP_LINES_TMP { get; set; }
    }
}
