//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_GP_LINES_TMP
    {
        public int gplt_id { get; set; }
        public string inv_number { get; set; }
        public int gp_id { get; set; }
    
        public virtual FDR_GP_HEADER FDR_GP_HEADER { get; set; }
        public virtual FDR_MSTR_INVOICE FDR_MSTR_INVOICE { get; set; }
    }
}
