//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_ORDSTAT_VIEW1
    {
        public int ord_stat_log_id { get; set; }
        public string ord_number { get; set; }
        public int logt_id { get; set; }
        public System.DateTime ord_stat_datetime { get; set; }
        public int usr_id { get; set; }
        public string logt_name { get; set; }
        public string usr_username { get; set; }
    }
}
