//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_SLSMAN_VIEW
    {
        public string salesman_id { get; set; }
        public string salesman_name { get; set; }
        public int salesman_type_id { get; set; }
        public string salesman_type_name { get; set; }
        public string site_id { get; set; }
        public string site_name { get; set; }
        public System.DateTime salesman_datecrtd { get; set; }
        public Nullable<System.DateTime> salesman_dateuptd { get; set; }
        public int salesman_crtdby { get; set; }
        public Nullable<int> salesman_uptdby { get; set; }
        public string crtdby { get; set; }
        public string uptdby { get; set; }
    }
}
