//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_INVOICE_VIEW
    {
        public string inv_number { get; set; }
        public System.DateTime inv_date { get; set; }
        public string ord_number { get; set; }
        public string cust_id { get; set; }
        public string cust_name { get; set; }
        public double inv_amount { get; set; }
        public System.DateTime inv_uplddate { get; set; }
        public string salesman_name { get; set; }
        public string upldby { get; set; }
    }
}
