//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_MSTR_DEV
    {
        public int dev_id { get; set; }
        public string dev_name { get; set; }
        public string dev_model { get; set; }
        public string dev_serial { get; set; }
        public int stat_id { get; set; }
        public Nullable<System.DateTime> dev_firstsynced { get; set; }
        public Nullable<System.DateTime> dev_lastsynced { get; set; }
        public Nullable<System.DateTime> dev_registered { get; set; }
        public Nullable<int> dev_rgstrdby { get; set; }
        public Nullable<System.DateTime> dev_dateuptd { get; set; }
        public Nullable<int> dev_uptdby { get; set; }
    
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS1 { get; set; }
        public virtual FDR_TYPE_STAT FDR_TYPE_STAT { get; set; }
    }
}
