//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_MSTR_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDR_MSTR_INVOICE()
        {
            this.FDR_GP_LINES = new HashSet<FDR_GP_LINES>();
            this.FDR_GP_LINES_TMP = new HashSet<FDR_GP_LINES_TMP>();
        }
    
        public string inv_number { get; set; }
        public string ord_number { get; set; }
        public double inv_amount { get; set; }
        public System.DateTime inv_uplddate { get; set; }
        public System.DateTime inv_date { get; set; }
        public int inv_upldby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_GP_LINES> FDR_GP_LINES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDR_GP_LINES_TMP> FDR_GP_LINES_TMP { get; set; }
        public virtual FDR_MSTR_USRS FDR_MSTR_USRS { get; set; }
        public virtual FDR_ORD_HEADER FDR_ORD_HEADER { get; set; }
    }
}
