//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDR_GP_LINES
    {
        public int gpl_id { get; set; }
        public string inv_number { get; set; }
        public int gp_id { get; set; }
        public int rcv_id { get; set; }
        public Nullable<double> gpl_payment { get; set; }
        public Nullable<double> gpl_redamnt { get; set; }
        public Nullable<int> dels_id { get; set; }
        public Nullable<double> gpl_pdamnt { get; set; }
    
        public virtual FDR_GP_HEADER FDR_GP_HEADER { get; set; }
        public virtual FDR_MSTR_INVOICE FDR_MSTR_INVOICE { get; set; }
        public virtual FDR_TYPE_DEL FDR_TYPE_DEL { get; set; }
        public virtual FDR_TYPE_RCVD FDR_TYPE_RCVD { get; set; }
    }
}
