//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FeederMasterDB : DbContext
    {
        public FeederMasterDB()
            : base("name=FeederMasterDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<FDR_BARCODE> FDR_BARCODE { get; set; }
        public virtual DbSet<FDR_CO_HEADER> FDR_CO_HEADER { get; set; }
        public virtual DbSet<FDR_CO_LINES> FDR_CO_LINES { get; set; }
        public virtual DbSet<FDR_CRR_DENO> FDR_CRR_DENO { get; set; }
        public virtual DbSet<FDR_GP_HEADER> FDR_GP_HEADER { get; set; }
        public virtual DbSet<FDR_GP_LINES> FDR_GP_LINES { get; set; }
        public virtual DbSet<FDR_GP_LINES_TMP> FDR_GP_LINES_TMP { get; set; }
        public virtual DbSet<FDR_MSTR_CUST> FDR_MSTR_CUST { get; set; }
        public virtual DbSet<FDR_MSTR_DEV> FDR_MSTR_DEV { get; set; }
        public virtual DbSet<FDR_MSTR_INVOICE> FDR_MSTR_INVOICE { get; set; }
        public virtual DbSet<FDR_MSTR_INVTY> FDR_MSTR_INVTY { get; set; }
        public virtual DbSet<FDR_MSTR_JRSLSMAN> FDR_MSTR_JRSLSMAN { get; set; }
        public virtual DbSet<FDR_MSTR_SITE> FDR_MSTR_SITE { get; set; }
        public virtual DbSet<FDR_MSTR_SLSMAN> FDR_MSTR_SLSMAN { get; set; }
        public virtual DbSet<FDR_MSTR_USRS> FDR_MSTR_USRS { get; set; }
        public virtual DbSet<FDR_ORD_HEADER> FDR_ORD_HEADER { get; set; }
        public virtual DbSet<FDR_ORD_LINES> FDR_ORD_LINES { get; set; }
        public virtual DbSet<FDR_ORD_STATUS_LOG> FDR_ORD_STATUS_LOG { get; set; }
        public virtual DbSet<FDR_TYPE_CO> FDR_TYPE_CO { get; set; }
        public virtual DbSet<FDR_TYPE_DEL> FDR_TYPE_DEL { get; set; }
        public virtual DbSet<FDR_TYPE_GPSTAT> FDR_TYPE_GPSTAT { get; set; }
        public virtual DbSet<FDR_TYPE_LOG> FDR_TYPE_LOG { get; set; }
        public virtual DbSet<FDR_TYPE_RCVD> FDR_TYPE_RCVD { get; set; }
        public virtual DbSet<FDR_TYPE_SLSMAN> FDR_TYPE_SLSMAN { get; set; }
        public virtual DbSet<FDR_TYPE_STAT> FDR_TYPE_STAT { get; set; }
        public virtual DbSet<FDR_TYPE_UOM> FDR_TYPE_UOM { get; set; }
        public virtual DbSet<FDR_TYPE_USRS> FDR_TYPE_USRS { get; set; }
        public virtual DbSet<FDR_CO_VIEW> FDR_CO_VIEW { get; set; }
        public virtual DbSet<FDR_CRRDET_VIEW> FDR_CRRDET_VIEW { get; set; }
        public virtual DbSet<FDR_CUST_VIEW> FDR_CUST_VIEW { get; set; }
        public virtual DbSet<FDR_DEV_VIEW> FDR_DEV_VIEW { get; set; }
        public virtual DbSet<FDR_GATEPASS_VIEW1> FDR_GATEPASS_VIEW1 { get; set; }
        public virtual DbSet<FDR_GPHEADER_VIEW> FDR_GPHEADER_VIEW { get; set; }
        public virtual DbSet<FDR_GPLINES_TMP_VIEW> FDR_GPLINES_TMP_VIEW { get; set; }
        public virtual DbSet<FDR_GPLINES_VIEW> FDR_GPLINES_VIEW { get; set; }
        public virtual DbSet<FDR_INVOICE_VIEW> FDR_INVOICE_VIEW { get; set; }
        public virtual DbSet<FDR_INVTY_VIEW> FDR_INVTY_VIEW { get; set; }
        public virtual DbSet<FDR_ITMGUIDE_VIEW1> FDR_ITMGUIDE_VIEW1 { get; set; }
        public virtual DbSet<FDR_ITMGUIDE_VIEW2> FDR_ITMGUIDE_VIEW2 { get; set; }
        public virtual DbSet<FDR_JRSLSMAN_VIEW> FDR_JRSLSMAN_VIEW { get; set; }
        public virtual DbSet<FDR_ORDNUMBER_VIEW> FDR_ORDNUMBER_VIEW { get; set; }
        public virtual DbSet<FDR_ORDSTAT_VIEW1> FDR_ORDSTAT_VIEW1 { get; set; }
        public virtual DbSet<FDR_ORDSTAT_VIEW2> FDR_ORDSTAT_VIEW2 { get; set; }
        public virtual DbSet<FDR_PRCNT_VIEW1> FDR_PRCNT_VIEW1 { get; set; }
        public virtual DbSet<FDR_PRCNT_VIEW2> FDR_PRCNT_VIEW2 { get; set; }
        public virtual DbSet<FDR_PRCNT_VIEW3> FDR_PRCNT_VIEW3 { get; set; }
        public virtual DbSet<FDR_SITE_VIEW> FDR_SITE_VIEW { get; set; }
        public virtual DbSet<FDR_SLSMAN_VIEW> FDR_SLSMAN_VIEW { get; set; }
        public virtual DbSet<FDR_USRS_VIEW> FDR_USRS_VIEW { get; set; }
    
        public virtual ObjectResult<ActivityPerformance_Result> ActivityPerformance(string orddate)
        {
            var orddateParameter = orddate != null ?
                new ObjectParameter("orddate", orddate) :
                new ObjectParameter("orddate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActivityPerformance_Result>("ActivityPerformance", orddateParameter);
        }
    }
}
