//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_GRPLVL2_VIEW
    {
        public int grpdl2_id { get; set; }
        public int grp_id { get; set; }
        public string grp_name { get; set; }
        public int s1mod_id { get; set; }
        public string s1mod_name { get; set; }
        public string stat_desc { get; set; }
        public int mod_id { get; set; }
    }
}
