//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_MSTR_DVMR
    {
        public int dvmr_id { get; set; }
        public System.DateTime dvmr_load_date { get; set; }
        public string site_code { get; set; }
        public System.DateTime dvmr_rdd { get; set; }
        public string dvmr_shipment { get; set; }
        public string dvmr_shipping_line { get; set; }
        public string dvmr_truck_no { get; set; }
        public string dvmr_cvan { get; set; }
        public string dvmr_salesdoc { get; set; }
        public string dvmr_po_number { get; set; }
        public string dvmr_billdoc { get; set; }
        public string dvmr_category { get; set; }
        public string invty_id { get; set; }
        public int dvmr_qty { get; set; }
        public Nullable<System.DateTime> dvmr_date_added { get; set; }
        public string dvmr_customer { get; set; }
        public Nullable<System.DateTime> dvmr_schedule_date { get; set; }
    }
}
