//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_INC_LINES
    {
        public int inc_line_id { get; set; }
        public string billdoc { get; set; }
        public string invty_id { get; set; }
        public Nullable<int> qty { get; set; }
        public string remarks { get; set; }
    }
}
