//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_MSTR_USRS
    {
        public int usr_id { get; set; }
        public string usr_username { get; set; }
        public string usr_password { get; set; }
        public string usr_fname { get; set; }
        public string usr_lname { get; set; }
        public int usr_type_id { get; set; }
        public int stat_id { get; set; }
        public System.DateTime usr_datecrtd { get; set; }
        public Nullable<System.DateTime> usr_dateuptd { get; set; }
        public int usr_crtdby { get; set; }
        public Nullable<int> usr_uptdby { get; set; }
        public int grp_id { get; set; }
    }
}
