//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_MSTR_UGRP
    {
        public int grp_id { get; set; }
        public string grp_name { get; set; }
        public System.DateTime grp_datecrtd { get; set; }
        public int grp_crtdby { get; set; }
        public int stat_id { get; set; }
        public Nullable<System.DateTime> grp_dateuptd { get; set; }
        public Nullable<int> grp_uptdby { get; set; }
    }
}
