//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_MSTR_JRSLSMAN
    {
        public int drvr_id { get; set; }
        public string drvr_name { get; set; }
        public string drvr_plate { get; set; }
        public int usr_id { get; set; }
        public int salesman_type_id { get; set; }
        public System.DateTime drvr_datecrtd { get; set; }
        public Nullable<System.DateTime> drvr_dateuptd { get; set; }
        public int drvr_crtdby { get; set; }
        public Nullable<int> drvr_uptdby { get; set; }
        public string site_id { get; set; }
    }
}
