//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_SITE_VIEW
    {
        public string site_id { get; set; }
        public string site_name { get; set; }
        public System.DateTime site_datecrtd { get; set; }
        public Nullable<System.DateTime> site_dateuptd { get; set; }
        public int site_crtdby { get; set; }
        public Nullable<int> site_uptdby { get; set; }
        public string crtdby { get; set; }
        public string uptdby { get; set; }
    }
}
