//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_MSTR_LVL1M
    {
        public int lvl1mod_id { get; set; }
        public Nullable<int> mod_id { get; set; }
        public Nullable<int> usr_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<int> added_by { get; set; }
    }
}
