//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_MSTR_MODULE
    {
        public int mod_id { get; set; }
        public string mod_name { get; set; }
        public System.DateTime mod_datecrtd { get; set; }
        public int mod_crtdby { get; set; }
        public Nullable<System.DateTime> mod_dateuptd { get; set; }
        public Nullable<System.DateTime> mod_uptdby { get; set; }
        public int stat_id { get; set; }
    }
}
