//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_LVL1M_VIEW
    {
        public Nullable<int> usr_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> mod_id { get; set; }
        public string mod_name { get; set; }
        public string stat_desc { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<int> added_by { get; set; }
        public string Expr1 { get; set; }
    }
}
