//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wms.Entity_Class
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using wms.Forms;

    public partial class wmsdb : DbContext
    {
        public wmsdb()
            : base(Select_Server_Form.dbconn)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WMS_MSTR_CUST> WMS_MSTR_CUST { get; set; }
        public virtual DbSet<WMS_MSTR_INVTY> WMS_MSTR_INVTY { get; set; }
        public virtual DbSet<WMS_MSTR_SITE> WMS_MSTR_SITE { get; set; }
        public virtual DbSet<WMS_MSTR_SLSMAN> WMS_MSTR_SLSMAN { get; set; }
        public virtual DbSet<WMS_MSTR_USRS> WMS_MSTR_USRS { get; set; }
        public virtual DbSet<WMS_TYPE_SLSMAN> WMS_TYPE_SLSMAN { get; set; }
        public virtual DbSet<WMS_TYPE_USRS> WMS_TYPE_USRS { get; set; }
        public virtual DbSet<WMS_TYPE_STAT> WMS_TYPE_STAT { get; set; }
        public virtual DbSet<WMS_USRS_VIEW> WMS_USRS_VIEW { get; set; }
        public virtual DbSet<WMS_INVTY_VIEW> WMS_INVTY_VIEW { get; set; }
    }
}
